version: '3.7'
services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - data:/data/db
    ports:
        - 27017:27017

volumes:
  data:
    driver: local